### ISSUE TITLE
Fiora not running

### ISSUE THREAD

**Issue by axkim3** [BAMeScience/fiora#3]
Hi, I'm receiving errors while trying to run the Fiora code on my laptop (MacBook M1 Pro). I have all of the files in the same directory.

Below is a screenshot + copied text of the error:

<img width="1512" alt="Screen Shot 2024-07-01 at 10 34 46 PM" src="https://github.com/BAMeScience/fiora/assets/62306073/8265c80a-4136-4be8-9bbc-3671dc342ba9">

(base) andrewkim@Andrews-MacBook-Pro-3656 share % fiora-predict -i examples/example_input.csv -o examples/expected_output.txt --model share/v0.0.1_merged_depth6_Jan24+CCS+RT.pt --rt --ccs --annotation 

Running fiora prediction with the following parameters: Namespace(input='examples/example_input.csv', output='examples/expected_output.txt', model='share/v0.0.1_merged_depth6_Jan24+CCS+RT.pt', dev='cpu', rt=True, ccs=True, annotation=True)

Warning: Failed loading the model share/v0.0.1_merged_depth6_Jan24+CCS+RT.pt. Fallback: Loading the model from state dictionary.
Error: Failed loading from state dict.

**Comment by ch4perone** [comment]
Hi Andrew,
are you 100% sure the paths are correct? This error message is also raised when the model file doesn't exist. It looks like you are running _fiora_ from the share directory, so the local path might be wrong. I recommend running it from home directory and explicitly specifying the complete paths to the model and data.

Otherwise, I will update the script to provide a more informative error message in the next patch to narrow down the problem. Due to server issues we are facing, this might take a day or two.

**Comment by axkim3** [comment]
Hi,

I tried running from the home directory and specifying exact paths to the model + data, and got the same error:

![Screen Shot 2024-07-03 at 2 46 49 PM](https://github.com/BAMeScience/fiora/assets/62306073/f01b9f4d-a4bd-4b5a-97a4-fa9ae5b14c2f)

If you could update the script for a more informative error message, that would be very helpful. Thank you so much!

**Comment by ch4perone** [comment]
Hi,

can you pull and run **fiora** again (_main_ branch). I added the exception output.

e.g. for missing file it looks like this
![Screenshot from 2024-07-05 11-14-53](https://github.com/BAMeScience/fiora/assets/21035221/3db36136-ad36-4f07-8a82-eea3c9395f4f)

**Comment by axkim3** [comment]
Hi Yannek,

Here's a screenshot + text of the error we discussed today,

<img width="806" alt="Screen Shot 2024-07-10 at 12 14 07 PM" src="https://github.com/BAMeScience/fiora/assets/62306073/6a0c1675-9289-4fb5-9d14-d412e8271986">

(base) andrewkim@Andrews-MacBook-Pro-3656 ~ % fiora-predict -i Documents/fiora/examples/example_input.csv -o Documents/fiora/examples/example_spec.mgf --model Documents/fiora/share/v0.0.1_merged_depth6_Jan24+CCS+RT.pt --no-rt --no-ccs
Running fiora prediction with the following parameters: Namespace(input='Documents/fiora/examples/example_input.csv', output='Documents/fiora/examples/example_spec.mgf', model='Documents/fiora/share/v0.0.1_merged_depth6_Jan24+CCS+RT.pt', dev='cpu', rt=False, ccs=False, annotation=False)

Warning: Failed loading the model Documents/fiora/share/v0.0.1_merged_depth6_Jan24+CCS+RT.pt. Fallback: Loading the model from state dictionary.
Error: Failed loading from state dict. Caused by: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU..

Thank you, and have a great holiday!
-Andrew
