### ISSUE TITLE
question about the pretrained model

### ISSUE THREAD

**Issue by zbjzbj001** [BAMeScience/fiora#5]
hellow! i'm vary interested in fiora since it can predict the spectra in negative ion mode. but it seems the model can't work with out a pretained model file, is it available now?

**Comment by ch4perone** [comment]
Hi, I will upload a pre-trained open-source model very soon (in about a week or two).

**Comment by ch4perone** [comment]
An open-source model is now available in the `models` directory and is set as the default model. Additionally, a release version has been created. Please note that, as this is the initial release, there may still be some bugs and performance issues. Let me know if you encounter any issues.
